### ISSUE TITLE
Automatic ETag 304 responses trigger HTML 500 responses

### ISSUE THREAD

**Issue by ChristianAlexander** [skonves/openapi-router#5]
Repro is live at https://openapi-router-304-bug.glitch.me
Repro source is at https://glitch.com/edit/#!/openapi-router-304-bug

**Expected behavior**
* Express-generated 304 responses should not trigger a 500 error
* Express-generated 304 responses should not return HTML
* 304 should not need to be a response code in the swagger document

**Actual behavior**
Express automatically sends a 304 when the `If-None-Match` header is equal to the generated `ETag` for the response. This triggers an alternating pattern of successful responses (when the browser does not send the `If-None-Match` header) and unsuccessful ones (with the header added).

When a response is a 304, and the openapi spec for the endpoint does not contain the 304 status code, the server returns a 500 with the following content:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>[object Object]</pre>
</body>
</html>
```

**Comment by skonves** [comment]
View fix at: https://ivory-ox.glitch.me/
(code: https://glitch.com/edit/#!/ivory-ox)
